input {
  file {
    path => "/usr/share/logstash/data/training.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

filter {
  mutate {
    add_field => {
      "lab" => "lab6"
      "pipeline" => "elk_ml_training"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "lab6-training-logs"
  }
  stdout {
    codec => rubydebug
  }
}
